# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment1Grams',
            fields=[
                ('phrase', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment2Grams',
            fields=[
                ('phrase', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment3Grams',
            fields=[
                ('phrase', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
    ]
